name: Test Secrets

on:
  workflow_dispatch:  # allows manual run

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "ACCESS_TOKEN length: ${ACCESS_TOKEN:?not set}"
          echo "PHONE_NUMBER_ID: ${PHONE_NUMBER_ID:?not set}"
          echo "RECIPIENT_NUMBER: ${RECIPIENT_NUMBER:?not set}"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
          RECIPIENT_NUMBER: ${{ secrets.RECIPIENT_NUMBER }}
